- hosts: webservers
  become: yes
  vars:
    http_port: 8000
    https_port: 4443
    html_welcome_msg: "Hello Guys, Welcome to Ansible Automation"
    domain_name: "example.com"  # Customizable domain
  tasks:
  - name: Ensure Apache is installed and at the latest version
    apt:
      name: apache2
      state: latest
      update_cache: yes  # Ensures package list is fresh
  
  - name: Enable Apache SSL module
    apache2_module:
      name: ssl
      state: present
    notify: restart apache

  - name: Configure Apache ports.conf
    template:
      src: templates/ports.conf.j2
      dest: /etc/apache2/ports.conf
      owner: root
      group: root
      mode: "0644"
    notify: restart apache

  - name: Deploy custom index.html
    template:
      src: templates/index.html.j2
      dest: /var/www/html/index.html
      owner: www-data
      group: www-data
      mode: "0644"
    notify: restart apache

  - name: Ensure Apache service is running and enabled
    service:
      name: apache2
      state: started
      enabled: yes  # Starts on boot

  - name: Open HTTP and HTTPS ports in UFW (Ubuntu firewall)
    ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
    loop:
      - "{{ http_port }}"
      - "{{ https_port }}"

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted